### ISSUE TITLE
Feature request: have tags actually add tags in obsidian.

### ISSUE THREAD

**Issue by legolasdimir** [huseyz/obsidian-wallabag#18] opened 2023-07-17 20:14 UTC
I am testing this plugin as I'm an avid user of wallabag and Obsidian and want to create a connected workflow between the two. Would it be possible to get this plugin to create actual tags in Obsidian instead of just a comma-separated list of strings?

**Comment by huseyz** [comment] 2023-07-17 20:17
I just implemented this 3 mins ago; nice coincidence. Also a duplicate of https://github.com/huseyz/obsidian-wallabag/issues/13

**Closed by huseyz** 2023-07-17 20:17 UTC

**Comment by legolasdimir** [comment] 2023-07-17 20:24
@huseyz has the plugin files been updated so we can install and update your plugin with BRAT?

**Comment by huseyz** [comment] 2023-07-17 20:28
Release 0.1.5 includes the setting for this now. https://github.com/huseyz/obsidian-wallabag/releases/tag/0.1.5
I don't have any experience with BRAT tho.

**Comment by legolasdimir** [comment] 2023-07-17 20:39
im not sure why but when I try I see something about main.js missing from the release. you might want to ask on discord. you might get more traction for your plugin that way.

**Comment by huseyz** [comment] 2023-07-17 20:47
The latest release works for me. Just putting the files from the latest release to your plugin folder is enough.
